### ISSUE TITLE
OpenAPI spec documentation?

### ISSUE THREAD

**Issue by magick93** [SaxoBank/openapi-samples-feature#26]
Hello

Does the Saxo Bank OpenAPI have [OpenAPI](https://www.openapis.org/) compliant docs?

The reason for asking is, using openapi docs can dramatically speed up implementation time. We are able to use various tools from the openapi eco system to generate, for example, client code.

Thanks

**Comment by BJOSAXO** [comment]
Hi magic93. We are certainly considering this. One of the things we are looking into is how to accomodate for a number of our nonstandard extensions, such as streaming.

Regards,,

Benny
